const markdownIt = require('markdown-it');
const esbuild = require('./_utilities/esbuild.js');
const lightingcss = require('./_utilities/lightningcss.js');
const image = require('./_utilities/image.js');
const style = require('./_utilities/style.js');
const setVar = require('./_utilities/setVar.js');
const fullDate = require('./_utilities/fullDate.js');
const getRandom = require('./_utilities/getRandom.js');
const markdownify = require('./_utilities/markdownify.js');
const sortBy = require('./_utilities/sortBy.js');
const where = require('./_utilities/where.js');
const htmlmin = require('html-minifier-terser');
const { isProduction, isStaging } = require('./_data/env.js');

module.exports = function (eleventyConfig) {
  /* --------------------------------------------------------------------------
  Plugins, shortcodes, filters
  -------------------------------------------------------------------------- */
  eleventyConfig.addPlugin(esbuild);
  eleventyConfig.addPlugin(lightingcss);
  eleventyConfig.addShortcode('image', image);
  eleventyConfig.addPairedShortcode('setVar', setVar);
  eleventyConfig.addPairedShortcode('style', style);
  eleventyConfig.addFilter('fullDate', fullDate);
  eleventyConfig.addFilter('getRandom', getRandom);
  eleventyConfig.addFilter('markdownify', markdownify);
  eleventyConfig.addFilter('sortBy', sortBy);
  eleventyConfig.addFilter('where', where);

  /* --------------------------------------------------------------------------
Dev Server settings
-------------------------------------------------------------------------- */

  eleventyConfig.setServerOptions({
    domDiff: true,
    watch: ["_site/assets/css/tailwind.css"],
  });

  /* --------------------------------------------------------------------------
  MarkdownIt settings
  -------------------------------------------------------------------------- */
  const markdownItOptions = {
    html: true,
    typographer: true,
  };
  eleventyConfig.setLibrary('md', markdownIt(markdownItOptions));


  /* --------------------------------------------------------------------------
  Minify HTML in Production
  -------------------------------------------------------------------------- */
  if (isProduction || isStaging) {
    eleventyConfig.addTransform('html-minify', (content, path) => {
      if (path && path.endsWith('.html')) {
        return htmlmin.minify(
          content, {
          collapseBooleanAttributes: true,
          collapseWhitespace: true,
          decodeEntities: true,
          includeAutoGeneratedTags: false,
          removeComments: true,

        }
        );
      }

      return content;
    });
  }

  /* --------------------------------------------------------------------------
  Files & folders
  -------------------------------------------------------------------------- */
  eleventyConfig.addPassthroughCopy('./assets/fonts');
  eleventyConfig.addPassthroughCopy({ "./assets/static": "/" });
  eleventyConfig.addPassthroughCopy('./assets/images');



  return {
    dir: {
      input: 'content',
      output: '_site',
      layouts: '../_includes/_layouts',
      includes: '../_includes',
    },
    templateFormats: ['html', 'md', 'liquid'],
    htmlTemplateEngine: 'liquid',
  };
};
